repos:
   -   repo: https://github.com/pycqa/isort
       rev: 5.10.1
       hooks:
         - id: isort
           name: isort (python)
           args:
             - "--profile=black"

   -   repo: https://github.com/psf/black
       rev: 22.10.0
       hooks:
         - id: black
           args:
             - --line-length=88
             - --include='\.pyi?$'

   -   repo: https://github.com/pycqa/flake8
       rev: 5.0.4
       hooks:
         - id: flake8
           args:
             - "--max-line-length=88"
             - "--max-complexity=18"
             - "--select=B,C,E,F,W,T4,B9,c90"
             - "--ignore=E203,E266,E501,W503,F403,F401,E402"

default_language_version:
    python: python3.10
